# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.parent_generator:
        class: AppBundle\Service\ParentGenerator
        arguments: ["@=service('doctrine.orm.gramweb_entity_manager')"]
    app.assmat_service:
        class: AppBundle\Service\AssmatService
        arguments: ["@=service('doctrine.orm.gramweb_entity_manager')"]
    app.user_service:
        class: AppBundle\Service\User_raService
        arguments: ["@=service('doctrine.orm.default_entity_manager')","@=service('doctrine.orm.gramweb_entity_manager')" ]
    app.update_logs_service:
        class: AppBundle\Service\UpdateLogsService
        arguments: ["@=service('doctrine.orm.default_entity_manager')","@=service('doctrine.orm.gramweb_entity_manager')" ]

#    app.calendar_listener:
#        class: AppBundle\EventListener\CalendarEventListener
#        arguments: ["@=service('doctrine.orm.gramweb_entity_manager')"]
#        tags:
#            - { name: 'kernel.event_listener', event: 'calendar.load_events', method: 'loadEvents' }
#    app.famfile_servece:
#        class: AppBundle\Service\famfile_servece
#        arguments: ["@=service('dostrine.rom.default_entity_manager')","@=service('doctrine.orm.gramweb_entity_manager')"]